# Generated by Django 3.0 on 2022-03-07 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rferog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='commentsNumber',
        ),
        migrations.AddField(
            model_name='post',
            name='parent_topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rferog.Topic'),
        ),
    ]
