# Generated by Django 3.0 on 2022-03-13 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rferog', '0003_remove_post_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent_id',
            new_name='parent_comment_id',
        ),
    ]
