# Generated by Django 3.0 on 2022-03-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rferog', '0004_auto_20220313_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_comment_id',
            field=models.IntegerField(null=True),
        ),
    ]
