# Generated by Django 3.0 on 2022-03-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rferog', '0005_auto_20220313_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_comment_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
